services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://anlangthang:123456@mongo:27017/task-manager?authSource=admin
    depends_on:
      - mongo
  mongo:
    image: "mongo:latest"
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=anlangthang
      - MONGO_INITDB_ROOT_PASSWORD=123456

  # mongo-express: 
  #   image: mongo-express:latest
  #   container_name: mongo-express
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongo
  #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
  #     - ME_CONFIG_BASICAUTH_USERNAME=admin        
  #     - ME_CONFIG_BASICAUTH_PASSWORD=admin123 
volumes:
  mongo-data:
